pizzar/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^shops/', include('shops.urls')),
    url(r'^admin/', admin.site.urls),
]

shops/urls.py
from django.conf.urls import url

from . import views

app_name = 'shops'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<shop_id>[0-9]+)/$', views.detail, name='detail'),
]

shops/models.py
from django.db import models

class Style(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Shop(models.Model):
    name = models.CharField(max_length=100)
    readable_name = models.CharField(max_length=100)
    excerpt = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')
    style = models.ForeignKey(Style, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

shops/views.py
from django.shortcuts import render

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from .models import Shop


def index(request):
    shop_list = Shop.objects.order_by('-pub_date')[:5]
    context = {
        'shop_list': shop_list,
    }
    return render(request, 'shops/index.html', context)


def detail(request, shop_id):
    shop = get_object_or_404(Shop, pk=shop_id)
    return render(request, 'shops/detail.html', {'shop': shop})

shops/templates/shops/detail.html
{{ shop }}

shops/templates/shops/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'shops/style.css' %}" />

{% if shop_list %}
    <ul>
    {% for shop in shop_list %}
	    <li><a href="{% url 'shops:detail' shop.id %}">{{ shop.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No shops are available.</p>
{% endif %}